### ISSUE TITLE
Support usage with GraphQL query responses

### ISSUE THREAD

**Issue by davidhousedev** [intercom/contentful-typescript-codegen#17]
When using this library to add type information to the anticipated structure of GraphQL queries to Contentful, I found that this library doesn't quite support my use case.

There are two exported interfaces for each of the Contentful models. The `IModelNameFields` and `IModelName` interfaces. When I query with GraphQL, the model of the data is comprised entirely of interfaces matching the `IModelNameFields` signatures, rather than the `IModelName` interfaces. For modes that don't have any references, this is fine because I can simply declare that the GraphQL query structure will contain interfaces using `IModelNameFields`. However, if there is a relation where one model references another, the reference points to an `IModelName` interface.

For example, say you have a model `Blog` with a relation to a `Comment` model. If I do a GraphQL query for all `Comment`s, then I'm okay because I can use the `ICommentFields` interface. However, if I do a GraphQL query for `Blog`s, and I provide the `IBlogFields` interface, the interface will have a relation to `IComment`, which won't match the structure of the object I get back from GraphQL.

Might it be possible for this library to support my use case? As it stands now, I will need to override all of the relations for my models in the generated interfaces. This is significantly less work than maintaining entire interfaces myself, but I'd prefer for the interfaces generated to match 1:1.

Thanks!

**Comment by davidhousedev** [comment]
I'm going to take a crack on this in a fork, which I'm happy to contribute back upstream. Presently, I plan to add a new `renderer` and an accompanying `--props-only` flag which will render all interfaces without the top-level `field`.

Let me know if taking a different approach would make it easier to accept my contribution!

**Comment by stevenpetryk** [comment]
I think I understand the use case—you may want to query _just_ fields for everything, including references, but this library only gives you this structure:

```
ThingFields
  SubThingWithFieldsAndSys
    fields
    sys
```

Whereas you want

```
ThingFields
  SubThingFields
```

I'm hesitant to support this use case, because opening this library up to the world of GraphQL means that we'll have to shape the types based on the _query_, rather than Contentful's content model. For the sake of describing the problem, forget Contentful exists for a moment. Imagine an API has a `post` type with the following fields:

```gql
type Post {
  author: Author!
  title: String!
  body: String!
  permalink: String!
}
```

And imagine we generate the following TS declaration:

```ts
interface IPost {
  author: IAuthor
  title: string
  body: string
  permalink: string
}
```

But then we run the following _query_:

```gql
posts(id: 4) {
  title
  body
}
```

We **can't** say that the result here is an `IPost`, because it doesn't have `author` or `permalink`. So we need a new type to be generated based on the _query_, not the _schema_, which this library is in no position to do without significant modifications.

For your use case, do you think something like Apollo's TypeScript codegen could work better for you? You can point it at Contentful's GraphQL endpoint, and it will analyze your code and generated TypeScript interfaces that match your queries: https://github.com/apollographql/apollo-tooling

**Comment by davidhousedev** [comment]
Thank you @stevenpetryk , I totally see your hesitation and it makes sense to me. Thank you for pointing me in the direction of the Apollo tool! I don't think I'll be using that since we're using Gatsby, but I think that https://www.gatsbyjs.org/packages/gatsby-plugin-graphql-codegen/ could meet our needs far better than what would be partial support from this library.

Thanks again!

**Comment by stevenpetryk** [comment]
Glad you found the right tool for the job! And I super appreciate that you opened a PR :)

**Comment by sonia-y** [comment]
Actually facing a similar issue... originally was using graphql-code-generator to generate all of the contentful types, but the issue with Contentful's GraphQL schema is that all fields are nullable/optional, which doesn't allow us to really leverage TS very well since we need to do null-checks everywhere.

**Comment by davidhousedev** [comment]
@sonia-y we've since migrated to use graphql-code-generator too and I really like that everything is nullable because of preview environments. We found that we were encountering many type errors in preview environments (where validation hasn't run yet). I suppose if you only read published data and you require everything, the utility is lower :).
